#!/bin/bash
module load impi

# Email variables
EMAIL=sameer@ices.utexas.edu
BEG=
FIN=

# Data variables
DATA_DIR=/work/00921/biros/maverick/data/machine_learning/
DATA=uni3d
TR_FILE=uniform_3d_4m.bin
N=4000000
D=3
#DATA=susy
#TR_FILE=susy.icml.trn.X.bin
#N=4500000
#D=18

# No. of MPI tasks
TASKS_PER_NODE=20

# Determines amount of sampling
MULT=1

for NODES in 8 
do
TOT_TASKS=$((NODES*TASKS_PER_NODE))

for SIG in .1 
do
for RANK in 4096
do
SAMP=$((MULT*RANK))
cat <<EOS | sbatch
#!/bin/bash
#SBATCH -J $DATA.$RANK.$NODES          # job name
#SBATCH -o git$MULT.$DATA.h$SIG.r$RANK.n$NODES.t$TASKS_PER_NODE.out     # output and error file name (%j expands to jobID)
#SBATCH -n $TOT_TASKS          # total number of mpi tasks requested
#SBATCH -N $NODES          # total number of nodes (2 sockets / node)
#SBATCH -p vis            # queue (partition) -- normal, development, etc.
#SBATCH -t 0:05:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PADAS           # Project
#SBATCH --mail-user=$EMAIL
##SBATCH --mail-type=$BEG    # email me when the job starts
##SBATCH --mail-type=$FIN    # email me when the job finishes

cd ${WORK}/research/par_nystrom

ibrun ./nystrom.exe --dir $DATA_DIR --trdata $TR_FILE --ntrain $N --dim $D --sigma $SIG --rank $RANK --samp $SAMP --tn true
EOS

done #RANK for loop
done #SIG for loop

done #TASK for loop
