#!/bin/bash
module load impi

EMAIL=sameer@ices.utexas.edu
DATA_DIR=/work/00921/biros/maverick/data/machine_learning/
#DATA=uni3d
#TR_FILE=uniform_3d_4m.bin
#N=4000000
#D=3
#DATA=brain
#TR_FILE=brain.trn.10321920.246d.X.bin
#N=10321920
#D=246
DATA=higgs
TR_FILE=higgs.10.5M.28d.trn.X.bin
N=10500000
D=28
TASKS_PER_NODE=20
MULT=1

for NODES in 16 
do
TOT_TASKS=$((NODES*TASKS_PER_NODE))

for SIG in 1 2 3  
do
for RANK in 8192 32768
do
SAMP=$((MULT*RANK))
cat <<EOS | sbatch
#!/bin/bash
#SBATCH -J $DATA.$RANK.$NODES          # job name
#SBATCH -o $DATA.h$SIG.r$RANK.n$NODES.t$TASKS_PER_NODE.out       # output and error file name (%j expands to jobID)
#SBATCH -n $TOT_TASKS          # total number of mpi tasks requested
#SBATCH -N $NODES          # total number of nodes (2 sockets / node)
#SBATCH -p gpu             # queue (partition) -- normal, development, etc.
#SBATCH -t 1:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PADAS           # Project
#SBATCH --mail-user=$EMAIL
##SBATCH --mail-type=end    # email me when the job finishes


cd ${WORK}/research/par_nystrom

ibrun ./nystrom.exe --dir $DATA_DIR --trdata $TR_FILE --ntrain $N --dim $D --sigma $SIG --rank $RANK --samp $SAMP --tn true
EOS

done #RANK for loop
done #SIG for loop

done #TASK for loop
