#!/bin/bash
module load impi

EMAIL=sameer@ices.utexas.edu
DATA_DIR=/work/00921/biros/maverick/data/machine_learning/
DATA=uni3d
TR_FILE=uniform_3d_4m.bin
N=4000000
D=3
TASKS_PER_NODE=20

for NODES in 8 16 
do
TOT_TASKS=$((NODES*TASKS_PER_NODE))

for SIG in 0.05
do
for RANK in 2048 4096 8192 16384 32768
do
cat <<EOS | sbatch
#!/bin/bash
#SBATCH -J $DATA.$RANK.$NODES          # job name
#SBATCH -o $DATA.h$SIG.r$RANK.n$NODES.t$TASKS_PER_NODE.out       # output and error file name (%j expands to jobID)
#SBATCH -n $TOT_TASKS          # total number of mpi tasks requested
#SBATCH -N $NODES          # total number of nodes (2 sockets / node)
#SBATCH -p gpu             # queue (partition) -- normal, development, etc.
#SBATCH -t 1:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PADAS           # Project
#SBATCH --mail-user=$EMAIL
#SBATCH --mail-type=end    # email me when the job finishes


cd ${WORK}/research/par_nystrom

ibrun ./nystrom.exe --dir $DATA_DIR --trdata $TR_FILE --ntrain $N --dim $D --sigma $SIG --rank $RANK
EOS

done #RANK for loop
done #SIG for loop

done #TASK for loop
