#!/bin/bash
module load impi

EMAIL=sameer@ices.utexas.edu
DATA_DIR=/work/00921/biros/maverick/data/machine_learning/
DATA=cov
TR_FILE=covtype.libsvm.trn.X.bin
TR_LAB=covtype.libsvm.trn.y.bin
N=500000
D=54
NODES=2
TASKS=$((NODES*2))

for SIG in 0.05
do
for RANK in 16384 
do
cat <<EOS | sbatch
#!/bin/bash
#SBATCH -J kernRun          # job name
#SBATCH -o val.$DATA.h$SIG.r$RANK.n$NODES.out       # output and error file name (%j expands to jobID)
#SBATCH -n $TASKS          # total number of mpi tasks requested
#SBATCH -N $NODES          # total number of nodes (2 sockets / node)
#SBATCH -p gpu             # queue (partition) -- normal, development, etc.
#SBATCH -t 01:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PADAS           # Project
#SBATCH --mail-user=$EMAIL
#SBATCH --mail-type=end    # email me when the job finishes


cd ${WORK}/research/par_nystrom

ibrun valgrind ./nystrom.exe --dir $DATA_DIR --trdata $TR_FILE --trlabs $TR_LAB --ntrain $N --dim $D --sigma $SIG --rank $RANK
EOS

done #RANK for loop
done #SIG for loop

