#!/bin/bash
module load impi

EMAIL=sameer@ices.utexas.edu
DATA_DIR=/work/00921/biros/maverick/data/machine_learning/
DATA=susy
FILE_BASE=susy.icml
TR_FILE=$FILE_BASE.trn.X.bin
TR_LABS=$FILE_BASE.trn.y.bin
TE_FILE=$FILE_BASE.tst.X.bin
TE_LABS=$FILE_BASE.tst.y.bin
N=4500000
NTEST=500000
D=18
TASKS_PER_NODE=20
MULT=1
R_FLAG=true

for NODES in 16 
do
TOT_TASKS=$((NODES*TASKS_PER_NODE))

for SIG in 0.25
do
for RANK in 16384 8192 
do
SAMP=$((RANK*MULT))
cat <<EOS | sbatch
#!/bin/bash
#SBATCH -J $DATA.$RANK.$NODES          # job name
#SBATCH -o $DATA.h$SIG.r$RANK.s$SAMP.n$NODES.t$TASKS_PER_NODE.out       # output and error file name (%j expands to jobID)
#SBATCH -n $TOT_TASKS          # total number of mpi tasks requested
#SBATCH -N $NODES          # total number of nodes (2 sockets / node)
#SBATCH -p gpu             # queue (partition) -- normal, development, etc.
#SBATCH -t 1:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PADAS           # Project
#SBATCH --mail-user=$EMAIL
#SBATCH --mail-type=end    # email me when the job finishes


cd ${WORK}/research/par_nystrom

ibrun ./nystrom.exe --dir $DATA_DIR --trdata $TR_FILE --trlabs $TR_LABS --tedata $TE_FILE --telabs $TE_LABS --ntrain $N --ntest $NTEST --dim $D --sigma $SIG --rank $RANK --samp $SAMP --rr $R_FLAG 
EOS

done #RANK for loop
done #SIG for loop

done #TASK for loop
